# Generated by Django 4.0.4 on 2022-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_scan_delete_scan_list_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='document',
        ),
        migrations.AddField(
            model_name='documents',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(default=5, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
