# Generated by Django 4.0.4 on 2022-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_documents_document_documents_filepath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='scan',
            name='Client',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
