# Generated by Django 4.0.4 on 2022-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_scan_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='finished',
            field=models.DateTimeField(blank=True),
        ),
    ]
