# Generated by Django 4.0.4 on 2022-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_scan_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='finished',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.BooleanField(blank=True, default='Done'),
        ),
    ]
